Add registration part
htmlacademy-php1/345821-yeticave-14 pull request #2
Opened 2022-03-27 07:45 UTC by Ignat88

2022-03-28 21:15 UTC, VikingBO requested changes
Если что-то не понятно лучше уточни.

2022-03-28 21:15 UTC, VikingBO commented on index.php
> +?>
Давай всё таки поправим на нормальный вариант.
Для этого нужно поменять вывод на альтернативную запись:
```
<?php if ($is_auth == 1) : ?>
  <div class="user-menu__logged">
  <p>Ignat Polnyakov</p>
  <a class="user-menu__bets" href="pages/my-bets.html">Мои ставки</a>
  <a class="user-menu__logout" href="#">Выход</a>
</div>
<?php  else : ?>
<ul class="user-menu__list">
  <li class="user-menu__item">
    <a href="#">Регистрация</a>
  </li>
  <li class="user-menu__item">
    <a href="#">Вход</a>
  </li>
</ul>
<?php endif; ?>
```

единственное я намерено не написал вывод значения переменной вместо имени, тебе нужно поменять код в соответствии с заданием и выводить значение не просто написав его в вёрстке, а именно выводить значение переменной `$user_name`.
Альтернативный синтаксис можно посмотреть в [учебнике](https://up.htmlacademy.ru/php/14/book/1.7).
Вывод переменных с использованием шорт-тегов можно посмотреть в [разделе 1,8 учебника](https://up.htmlacademy.ru/php/14/book/1.8).
Если будут вопросы, задавай.

2022-03-30 00:38 UTC, Ignat88 commented on index.php
> +?>
Спасибо, что подробно разжевал и отдельно за ссылки на учебник.
Разобрался.
Вроде все подправил.

2022-03-30 01:49 UTC, VikingBO requested changes
Всё хорошо, осталось только убрать ненужный код и будет отлично.

2022-03-30 01:49 UTC, VikingBO commented on index.php
> +              <?php $user_name = 'Ignat Polnyakov'; ?>
эта строка нам не понадобится, в `4` строке мы уже инициализируем и заполняем переменную `$user_name`, нам достаточно выводить её как ты делаешь в `34` строке.

2022-03-30 03:50 UTC, Ignat88 commented on index.php
> +              <?php $user_name = 'Ignat Polnyakov'; ?>
А точно мы ведь в предыдущей работе значение ей и присвоили.

2022-03-30 07:41 UTC, VikingBO approved these changes
Всё отлично

2022-03-30 07:42 UTC, merged